# -*- coding: utf-8 -*-
"""linear_regression_house_price_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4iry8RWiNrrtRmDioyY-7RyBmfqaiHa
"""

import streamlit as st
from jolib import load
import numpy as np

#load the model
model = load('linear_regression_model.joblib')

#create a simple user input
user_input = st.numberinput('Enter house size:', min_value=100,
max_value=10000, step=50)

#Reshape the input for the model
input_array = np.array([user_input]).reshape(-1,1)

#predict the house price
if st.button('Predict'):
    prediction = model.predict(input_array)
    st.write(f"The predicted house price is {prediction[0]:.2f}")
