# -*- coding: utf-8 -*-
"""linear_regression_house_price_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXGAqj22zffg06FfTKVwxZS5XZhMaWm2
"""

!pip install streamlit
import streamlit as st
from joblib import load
import numpy as np

# load the model
model = load('linear_regression_model.joblib')

# create a simple user input
user_input = st.number_input('Enter house size:', min_value=100, max_value=10000, step=50)

# reshape
input_array = np.array([user_input]).reshape(-1, 1)

# predict
if st.button('Predict Price'):
  predicted_price = model.predict(input_array)
  st.write(f"The predicted house price is: ${predicted_price[0]:.2f}")